### PR TITLE
add try catch block to continue getting the nfts

### PR DESCRIPTION
**Pull request by veewoo**
add try-catch block to continue getting the nfts in case a request is fails

### CODE REVIEW

**Comment by primenumsdev** [comment]
Hi @hung-viet, thanks for contribution, what error did you receive?

Also, I am not sure if the try/catch you have added will catch the API request error, b/c the actual request happening here:

https://github.com/primenumsdev/solana-nft-tools/pull/2/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1L223

These lines that you wrapped in try/catch are populating batch body for the request.

And, I think library should not suppress the error, instead I believe this should be handled in a user code with a retry logic.

**Comment by veewoo** [comment]
> Hi @hung-viet, thanks for contribution, what error did you receive?
> 
> Also, I am not sure if the try/catch you have added will catch the API request error, b/c the actual request happening here:
> 
> https://github.com/primenumsdev/solana-nft-tools/pull/2/files#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1L223
> 
> These lines that you wrapped in try/catch are populating batch body for the request.
> 
> And, I think library should not suppress the error, instead I believe this should be handled in a user code with a retry logic.

Hi @primenumsdev 

Your project is amazing, but when I use the get multiple Nfts function if an Nft is broken, it will make the for loop to stop. which means I cannot get my Nft collection. I have tested with try-catch block and it works well. So I want to contribute to your project.

**Comment by primenumsdev** [comment]
Hey @hung-viet can you pls share NFT address so I can try to reproduce the issue?

**Comment by veewoo** [comment]
Sorry, It's actually a token. Here is the token that I'm talking about.
https://explorer.solana.com/address/CkV4VDyvtwPudc8qJCUx5C6fDHTjPz261kWsEQ7aBef8?cluster=devnet

**Comment by primenumsdev** [comment]
Hi @hung-viet sorry for long delay, I have added some error handling [here](https://github.com/primenumsdev/solana-nft-tools/commit/8f2e9895cb23c8d494c4acd05f7d06505b663df6), now it should return the response with an error.

**Comment by veewoo** [comment]
@primenumsdev It seems ok now, thanks

**Pull request closed without merging**
